In [22]:
import numpy as np
dim=2
np.zeros((dim, 1))

array([[ 0.],
       [ 0.]])

In [57]:
w, b, X, Y = np.array([[1],[2]]), 2, np.array([[1,2],[3,4]]), np.array([[1,0]])
print(Y)
print(b)
m=X.shape[1]
A=X
print(A)
print(A.shape[1])
print(A.shape[0])
A2=1/m*np.sum(A.reshape(A.shape[0],-1).T-Y)
print(A2)

[[1 0]]
2
[[1 2]
 [3 4]]
2
2
4.0


In [2]:

A=np.array([[56,0,4.4,68],
            [1.2,104,52,8],
            [1.8,135,99,0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [11]:
cal=A.sum(axis=0)
print(cal)#cal is used in broadcasting in matrix algebra

[  59.   239.   155.4   76.9]


In [13]:
percentage=100*A/cal.reshape(1,4)
print(percentage)
#same as
percentage1=100*A/cal
print(percentage1)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]
[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [24]:
a=np.random.randn(5)# called a rank 1 array, behaves oddly in matrix alegra
print(a)
print(a.T)

[-0.60881894  0.35638092  0.21517293  0.82431227  0.44693145]
[-0.60881894  0.35638092  0.21517293  0.82431227  0.44693145]


In [25]:
print(a.shape)

(5,)


In [27]:
a=a.reshape((5,1))
print(a.shape)

(5, 1)


In [18]:
a=np.random.randn(5,1) #column vector
print(a)
print(a.T)

[[ 0.89058327]
 [-0.79332994]
 [-0.8507618 ]
 [ 0.44775067]
 [-0.61775402]]
[[ 0.89058327 -0.79332994 -0.8507618   0.44775067 -0.61775402]]


In [19]:
assert(a.shape==(5,1))

In [6]:
img=np.random.randn(32,32,3)
print(img.shape)

(32, 32, 3)


In [7]:
x=img.reshape((32*32*3,1))
print(x.shape)

(3072, 1)


In [10]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
print(a)
b = np.random.randn(2, 1) # b.shape = (2, 1)
print(b)
c = a + b
print(c)
print(c.shape)

[[ 0.75022458  0.82202322  0.639435  ]
 [ 0.47082362 -0.37694761 -0.35176176]]
[[ 1.15092198]
 [ 0.41488378]]
[[ 1.90114656  1.9729452   1.79035699]
 [ 0.8857074   0.03793617  0.06312202]]
(2, 3)


In [11]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [17]:
X=np.random.randn(3,1)
print(X)
nx=np.array([1,2])
print(nx)
m=X*nx
print(m.shape)

[[ 1.32291021]
 [-1.07726398]
 [ 0.24084274]]
[1 2]
(3, 2)


In [19]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [20]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)

for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]
print(c.shape)

(12288, 45)


In [25]:
c=a+b.T
print(c.shape)

(3, 4)


In [26]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c.shape)

(3, 3)


In [29]:
a=1
b=2
c=3
u=a*b
v=a*c
w=b+c
j=u+v-w
print(j)
j2=(a-1)*(b+c)
print(j2)

0
0
